baseurl = "/"
languageCode = "en-us"
title = "SEQUIconsulting"
theme = "hugo-theme-casper"
disqusShortname = "spf13"
# Enable Google Analytics by inserting your tracking code
googleAnalytics = ""
# Define how many posts should appear on a site
paginate = 10
canonifyurls = true

[params]
  description = "consulenza di direzione ed organizzazione aziendale, affari internazionali"
  cover = "images/cover.jpg"
  author = "Samuele Sequi"
  authorlocation = "Ancona, Italy"
  authorwebsite = "https://sequiconsulting.com"
  bio= "my bio"
  logo = "images/logo.png"
  googleAnalyticsUserID = "UA-103957247-1"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  RSSLink = ""
  #githubName = "sequiconsulting"
  twitterName = "sam.sequi"
  facebookName = "sequiconsulting"
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = true
  [params.social]
  #  twitter = "your_twitter"
